backend:
  name: git-gateway
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "stimmen"
    label: "KI-Stimmen"
    folder: "content/stimmen"
    create: true
    slug: "{{title}}"
    fields:
      - { label: "Name", name: "title", widget: "string" }
      - { label: "Sprache", name: "sprache", widget: "select", options: ["Deutsch", "Englisch"] }
      - { label: "Typ", name: "typ", widget: "select", options: ["Weiblich", "Männlich", "Symbolisch"] }
      - { label: "Avatar Bild URL", name: "avatar", widget: "string" }
      - { label: "Audio Datei URL", name: "audio", widget: "string" }
      - { label: "Beschreibung", name: "beschreibung", widget: "text" }
